// Copyright 2024 The NativeLink Authors. All rights reserved.
//
// Licensed under the Functional Source License, Version 1.1, Apache 2.0 Future License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    See LICENSE file for details
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is @generated by prost-build.
/// / Request object for keep alive requests.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeepAliveRequest {
    /// / CPU load percentage: load_avg_1m / num_cpus * 100.
    /// / 0 means unknown (old workers that don't report load).
    #[prost(uint32, tag = "2")]
    pub cpu_load_pct: u32,
    /// / Performance-core CPU utilization percentage (0-100).
    /// / 0 means unknown (Linux or non-heterogeneous CPU).
    #[prost(uint32, tag = "3")]
    pub p_core_load_pct: u32,
    /// / Efficiency-core CPU utilization percentage (0-100).
    /// / 0 means unknown. 100 when no E-cores exist (P-core-only CPU).
    #[prost(uint32, tag = "4")]
    pub e_core_load_pct: u32,
}
/// / Request object for going away requests.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GoingAwayRequest {}
/// / Represents the initial request sent to the scheduler informing the
/// / scheduler about this worker's capabilities and metadata.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectWorkerRequest {
    /// / The list of properties this worker can support. The exact
    /// / implementation is driven by the configuration matrix between the
    /// / worker and scheduler.
    /// /
    /// / The scheduler may reject this worker if any property keys that
    /// / the scheduler is not configured to support, or may simply ignore
    /// / the unsupported properties.
    /// /
    /// / The details on how to use this property can be found here:
    /// / <https://github.com/TraceMachina/nativelink/blob/3147265047544572e3483c985e4aab0f9fdded38/nativelink-config/src/cas_server.rs>
    #[prost(message, repeated, tag = "1")]
    pub properties: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::platform::Property,
    >,
    /// / Prefix to use for worker IDs. This is primarily used for debugging
    /// / or for other systems to identify workers. The scheduler will always
    /// / append this prefix to the assigned worker_id followed by a UUIDv6.
    #[prost(string, tag = "2")]
    pub worker_id_prefix: ::prost::alloc::string::String,
    /// / Maximum number of inflight tasks this worker can cope with at one time
    /// / The default (0) means unlimited.
    #[prost(uint64, tag = "3")]
    pub max_inflight_tasks: u64,
    /// / This worker's CAS gRPC endpoint for peer blob serving.
    /// / If set, other workers can fetch blobs directly from this worker.
    /// / Example: "grpc://192.168.100.5:50081"
    #[prost(string, tag = "5")]
    pub cas_endpoint: ::prost::alloc::string::String,
    /// / Process-lifetime identifier for this worker, generated fresh at
    /// / process start and stable across reconnects within a single run.
    /// / The scheduler uses this to detect a NEW process registering on
    /// / a recycled CAS endpoint (e.g. after OOM / kill -9 / panic) and
    /// / wipe its prior locality_map entries — those entries point to
    /// / `mirror_blobs` that lived only in the dead process's memory.
    /// /
    /// / Backward compatibility: workers built before this field exists
    /// / will leave it as the proto3 default `0`. The scheduler treats
    /// / `0` as "always different" (conservative wipe on reconnect) so
    /// / stale locality data from the old binary cannot survive.
    /// / (#141: boot_epoch_id one-way wipe on worker restart)
    #[prost(uint64, tag = "7")]
    pub boot_epoch_id: u64,
}
/// / Per-digest info reported by workers in BlobsAvailableNotification.
/// / The previous `last_access_timestamp` field has been retired now that the
/// / scheduler trusts the locality map until explicit eviction; the tag is
/// / reserved so old workers stay wire-compatible.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobDigestInfo {
    /// / The digest of the blob.
    #[prost(message, optional, tag = "1")]
    pub digest: ::core::option::Option<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
}
/// / Notification that blobs are available on a worker for peer serving.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobsAvailableNotification {
    /// / The worker's CAS endpoint where these blobs can be fetched.
    #[prost(string, tag = "1")]
    pub worker_cas_endpoint: ::prost::alloc::string::String,
    /// / The digests of newly available blobs (kept for backward compat / simple notifications).
    #[prost(message, repeated, tag = "2")]
    pub digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    /// / If true, this is a full snapshot of all blobs in the worker's cache.
    /// / The server should replace its entire view for this endpoint with the
    /// / contents of this message (digest_infos + digests). If false, this is
    /// / an incremental update (new blobs only).
    #[prost(bool, tag = "3")]
    pub is_full_snapshot: bool,
    /// / Digests that have been evicted from the worker since the last update.
    /// / Only meaningful when is_full_snapshot == false.
    #[prost(message, repeated, tag = "4")]
    pub evicted_digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    /// / Per-digest info with LRU timestamps. When present, the server should
    /// / prefer this over the plain `digests` field.
    #[prost(message, repeated, tag = "5")]
    pub digest_infos: ::prost::alloc::vec::Vec<BlobDigestInfo>,
    /// / CPU load percentage: load_avg_1m / num_cpus * 100.
    /// / 0 means unknown (old workers that don't report load).
    #[prost(uint32, tag = "6")]
    pub cpu_load_pct: u32,
    /// / Digests of input root directories that are cached in this worker's
    /// / directory cache. The scheduler can give routing preference to workers
    /// / that already have the action's input_root_digest cached.
    /// / Also used for the full subtree snapshot (when is_full_subtree_snapshot=true,
    /// / this contains ALL directory digests including subtrees).
    #[prost(message, repeated, tag = "7")]
    pub cached_directory_digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    /// / Delta-encoded subtree updates since last notification.
    /// / When a cache entry is added, send ALL directory digests in its merkle tree.
    /// / When a cache entry is evicted, send ALL directory digests that were removed
    /// / (only those no longer present in ANY cached entry's merkle tree).
    #[prost(message, repeated, tag = "8")]
    pub added_subtree_digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    #[prost(message, repeated, tag = "9")]
    pub removed_subtree_digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    /// / True on the first notification after (re)connect — scheduler should
    /// / replace its cached_subtree_digests state rather than applying a delta.
    /// / In this case, cached_directory_digests (field 7) contains the full set
    /// / of all subtree digests.
    #[prost(bool, tag = "10")]
    pub is_full_subtree_snapshot: bool,
    /// / Performance-core CPU utilization percentage (0-100).
    /// / 0 means unknown (Linux or non-heterogeneous CPU).
    #[prost(uint32, tag = "11")]
    pub p_core_load_pct: u32,
    /// / Efficiency-core CPU utilization percentage (0-100).
    /// / 0 means unknown. 100 when no E-cores exist (P-core-only CPU).
    #[prost(uint32, tag = "12")]
    pub e_core_load_pct: u32,
    /// / Digests of blobs the worker is holding pinned in memory as a server
    /// / mirror (received via x-nativelink-mirror writes). The worker has no
    /// / disk copy and the server may not have a stable copy yet — the worker
    /// / is the only durable holder.
    /// /
    /// / On receiving these, the server MUST:
    /// /   1. Register them in the locality map (so reads can find them),
    /// /   2. For digests it does not already have stably stored, request an
    /// /      `UploadMissingBlobs` so the worker uploads the bytes back to the
    /// /      server's slow store.
    /// / Once the server has stably stored a digest it will broadcast a
    /// / `BlobsInStableStorage` for it; only that signal causes the worker to
    /// / drop the pin. This protects mirror blobs across server restarts —
    /// / the worker holds the only copy until the server is ready to receive.
    #[prost(message, repeated, tag = "13")]
    pub pinned_mirror_digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    /// / Current `mirror_blobs` total bytes held in memory on this worker.
    /// / Reported on every BlobsAvailable so the server's mirror writer
    /// / (`WorkerProxyStore`) can pre-check capacity before consuming a
    /// / source stream. `0` is reported by workers that don't have a CAS
    /// / server / mirror store (the absence of a pin map is indistinguishable
    /// / from "currently empty"); the server's picker treats `0` as
    /// / unknown when paired with `mirror_max_bytes = 0`.
    #[prost(uint64, tag = "14")]
    pub mirror_used_bytes: u64,
    /// / Configured `MIRROR_BLOBS_MAX_BYTES` cap on this worker. `0`
    /// / means unknown — the picker disables the capacity filter for
    /// / this endpoint.
    #[prost(uint64, tag = "15")]
    pub mirror_max_bytes: u64,
    /// / CURRENT snapshot of dispatcher-pushed mirror pins per source store.
    /// / Sorted by `store_id` ASCII so the server can binary-search per
    /// / FastSlowStore's `store_id` slice in `observe_pinned_mirror_ack`.
    /// /
    /// / DIFFERENT SEMANTICS from field 13 (`pinned_mirror_digests`).
    /// / Field 13 carries the per-tick DELTA of newly-acquired mirror
    /// / digests; the server reaction registers locality entries AND
    /// / triggers `request_missing_blob_uploads` (BACKFILL_COOLDOWN
    /// / bypass). Field 16 carries the FULL CURRENT snapshot of pins
    /// / the dispatcher pushed; the server reaction broadcasts to all
    /// / registered FastSlowStores via `observe_pinned_mirror_ack`,
    /// / each of which binary-searches its own `store_id` region and
    /// / removes server-side `EphemeralServerSidePin` entries that are
    /// / now confirmed held on the worker.
    /// /
    /// / Both fields coexist on the wire and have distinct lifetimes —
    /// / do NOT conflate.
    #[prost(message, repeated, tag = "16")]
    pub pinned_mirror_entries: ::prost::alloc::vec::Vec<MirrorPinEntry>,
}
/// / One entry of `BlobsAvailableNotification.pinned_mirror_entries`.
/// / Identifies a server-side dispatcher-pushed mirror pin by `(store_id,
/// / digest)`. The `store_id` matches the source FastSlowStore that
/// / `SmallBlobDispatcher` pushed the blob from; the server's broadcast
/// / to all registered FastSlowStores routes via this string.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MirrorPinEntry {
    /// / The digest the worker now holds in its `mirror_blobs` map.
    #[prost(message, optional, tag = "1")]
    pub digest: ::core::option::Option<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    /// / The source FastSlowStore identifier (matches the per-store config
    /// / `store_id`). Used by `observe_pinned_mirror_ack` to scope the
    /// / unpin to the SOURCE store. Validated server-side as non-empty +
    /// / `[a-z][a-z0-9_]*`.
    #[prost(string, tag = "2")]
    pub store_id: ::prost::alloc::string::String,
}
/// / One blob entry in a `BatchWriteSmallBlobsRequest`. Carries the digest,
/// / payload bytes, and source `store_id` so the worker can route the write
/// / to the correct `mirror_blobs` slot keyed by `(store_id, digest)`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmallBlobEntry {
    /// / The digest of the blob being pushed. The worker MUST verify
    /// / `data.len() == digest.size_bytes()` (the existing
    /// / `insert_mirror_blob` invariant) before accepting.
    #[prost(message, optional, tag = "1")]
    pub digest: ::core::option::Option<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    /// / The blob bytes. Capped at `SMALL_BLOB_THRESHOLD` per the
    /// / dispatcher precondition (16 KiB by default).
    #[prost(bytes = "bytes", tag = "2")]
    pub data: ::prost::bytes::Bytes,
    /// / The source FastSlowStore identifier so the worker can key the
    /// / resulting `mirror_blobs` entry by `(store_id, digest)`. Empty or
    /// / invalid `store_id` causes the worker to reject the entry.
    #[prost(string, tag = "3")]
    pub store_id: ::prost::alloc::string::String,
}
/// / A batch of small-blob writes pushed from the server's
/// / `SmallBlobDispatcher` to a worker. The worker writes each entry into
/// / `mirror_blobs` keyed by `(store_id, digest)`. The dispatcher uses
/// / zero-window opportunistic coalesce, so a single batch may contain
/// / 1..N entries from a short producer burst.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchWriteSmallBlobsRequest {
    /// / The blob entries in this batch. Bounded by `max_batch_bytes`
    /// / (default 256 KiB ⇒ ~16 entries at 16 KiB max).
    #[prost(message, repeated, tag = "1")]
    pub blobs: ::prost::alloc::vec::Vec<SmallBlobEntry>,
}
/// / Notification that blobs have been evicted from a worker.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobsEvictedNotification {
    /// / The worker's CAS endpoint from which these blobs were evicted.
    #[prost(string, tag = "1")]
    pub worker_cas_endpoint: ::prost::alloc::string::String,
    /// / The digests of evicted blobs.
    #[prost(message, repeated, tag = "2")]
    pub digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
}
/// / Request to touch (update access time) blobs on a worker to prevent eviction.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TouchBlobsRequest {
    /// / The digests of blobs to touch.
    #[prost(message, repeated, tag = "1")]
    pub digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
}
/// / Sent by the server to a worker requesting upload of blobs that are
/// / present on the worker but missing from the server's CAS. The worker
/// / should read each blob from its local FilesystemStore and upload it
/// / to the server via the existing GrpcStore (slow store) connection.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadMissingBlobsRequest {
    /// / Digests of blobs the server needs the worker to upload.
    #[prost(message, repeated, tag = "1")]
    pub digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
}
/// / A hint that a specific digest is available on one or more peer workers.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerHint {
    /// / The digest available on peers.
    #[prost(message, optional, tag = "1")]
    pub digest: ::core::option::Option<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    /// / gRPC endpoints of workers that have this blob.
    #[prost(string, repeated, tag = "2")]
    pub peer_endpoints: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// / One chunk of a streaming peer-hints emission. Carries up to
/// / `PEER_HINTS_PER_CHUNK` `PeerHint` entries plus the operation_id the
/// / hints were generated for (informational only — the worker does NOT key
/// / any state by operation_id; hints register directly into the worker's
/// / global `peer_locality_map` as chunks arrive). `sequence` is monotonic
/// / 0,1,2,... within one stream and `is_last` marks the terminal chunk.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerHintsChunk {
    /// / Up to PEER_HINTS_PER_CHUNK hints (worker-side default: 256).
    #[prost(message, repeated, tag = "1")]
    pub peer_hints: ::prost::alloc::vec::Vec<PeerHint>,
    /// / The scheduler-side operation_id these hints were generated for.
    /// / Diagnostics-only; the worker doesn't key state on it.
    #[prost(string, tag = "2")]
    pub operation_id: ::prost::alloc::string::String,
    /// / Monotonic sequence within one operation_id's hint stream.
    #[prost(uint32, tag = "3")]
    pub sequence: u32,
    /// / True on the FINAL chunk of one operation_id's stream.
    #[prost(bool, tag = "4")]
    pub is_last: bool,
}
/// / One chunk of a streaming `BlobsInStableStorage` broadcast (task #97).
/// / Carries up to BIS_DIGESTS_PER_CHUNK digests plus a server-allocated
/// / `broadcast_id` and a monotonic `sequence`. Workers ack via
/// / `Update::BisAck { broadcast_id, sequence }` so the server can drop
/// / unacked chunks from its per-worker resend buffer; chunks not acked
/// / before connection close are replayed on the next ConnectWorker.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobsInStableStorageChunk {
    /// / Up to BIS_DIGESTS_PER_CHUNK digests (server-side default: 4096).
    #[prost(message, repeated, tag = "1")]
    pub digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    /// / Server-allocated identifier of the broadcast event.
    #[prost(uint64, tag = "2")]
    pub broadcast_id: u64,
    /// / Monotonic sequence within one broadcast_id.
    #[prost(uint32, tag = "3")]
    pub sequence: u32,
    /// / True on the FINAL chunk of one broadcast.
    #[prost(bool, tag = "4")]
    pub is_last: bool,
}
/// / A streaming-message envelope shared across the cas->worker, scheduler->
/// / worker, and worker->scheduler chunk producers. Exactly ONE of the
/// / `oneof payload` arms is set; receivers route on the arm.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChunkedMessage {
    #[prost(oneof = "chunked_message::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<chunked_message::Payload>,
}
/// Nested message and enum types in `ChunkedMessage`.
pub mod chunked_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        PeerHints(super::PeerHintsChunk),
        #[prost(message, tag = "2")]
        BlobsInStableStorage(super::BlobsInStableStorageChunk),
    }
}
/// / The result of an ExecutionRequest.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteResult {
    /// / The `instance_name` this task was initially assigned to. This is set by the client
    /// / that initially sent the job as part of the BRE protocol.
    #[prost(string, tag = "1")]
    pub instance_name: ::prost::alloc::string::String,
    /// / The operation ID that was executed.
    #[prost(string, tag = "2")]
    pub operation_id: ::prost::alloc::string::String,
    /// / The actual response data.
    #[prost(oneof = "execute_result::Result", tags = "3, 4")]
    pub result: ::core::option::Option<execute_result::Result>,
}
/// Nested message and enum types in `ExecuteResult`.
pub mod execute_result {
    /// / The actual response data.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        /// / Result of the execution. See `build.bazel.remote.execution.v2.ExecuteResponse`
        /// / for details.
        #[prost(message, tag = "3")]
        ExecuteResponse(
            super::super::super::super::super::super::build::bazel::remote::execution::v2::ExecuteResponse,
        ),
        /// / An internal error. This is only present when an internal error happened that
        /// / was not recoverable. If the execution job failed but at no fault of the worker
        /// / it should not use this field and should send the error via execute_response.
        #[prost(message, tag = "4")]
        InternalError(super::super::super::super::super::super::google::rpc::Status),
    }
}
/// / The result of an ExecutionComplete.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteComplete {
    /// / The operation ID that was executed.
    #[prost(string, tag = "1")]
    pub operation_id: ::prost::alloc::string::String,
    /// / CPU load percentage: load_avg_1m / num_cpus * 100.
    /// / 0 means unknown (old workers that don't report load).
    #[prost(uint32, tag = "2")]
    pub cpu_load_pct: u32,
    /// / Performance-core CPU utilization percentage (0-100).
    /// / 0 means unknown (Linux or non-heterogeneous CPU).
    #[prost(uint32, tag = "3")]
    pub p_core_load_pct: u32,
    /// / Efficiency-core CPU utilization percentage (0-100).
    /// / 0 means unknown. 100 when no E-cores exist (P-core-only CPU).
    #[prost(uint32, tag = "4")]
    pub e_core_load_pct: u32,
}
/// / Result sent back from the server when a node connects.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectionResult {
    /// / The worker ID to place in the action results generated by this worker.
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
}
/// / Sent by the server to workers to confirm that blobs have been
/// / persisted to stable storage (FilesystemStore, not just MemoryStore).
/// / Workers should unpin matching blobs from their local CAS.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobsInStableStorage {
    #[prost(message, repeated, tag = "1")]
    pub digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
}
/// / Request to kill a running operation sent from the scheduler to a worker.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KillOperationRequest {
    /// / The the operation id for the operation to be killed.
    #[prost(string, tag = "1")]
    pub operation_id: ::prost::alloc::string::String,
}
/// / Communication from the scheduler to the worker.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateForWorker {
    #[prost(oneof = "update_for_worker::Update", tags = "1, 2, 3, 4, 5, 7, 8, 9, 10, 11")]
    pub update: ::core::option::Option<update_for_worker::Update>,
}
/// Nested message and enum types in `UpdateForWorker`.
pub mod update_for_worker {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Update {
        /// / This will be sent only as the first item in the stream after the node
        /// / has connected.
        #[prost(message, tag = "1")]
        ConnectionResult(super::ConnectionResult),
        /// / Message used to let the worker know that it is still alive as well
        /// / as check to see if the worker is still alive. The worker
        /// / may close the connection if the scheduler has not sent any messages
        /// / after some amount of time (configured in the scheduler's
        /// / configuration).
        #[prost(message, tag = "2")]
        KeepAlive(()),
        /// / Informs the worker about some work it should begin performing the
        /// / requested action.
        #[prost(message, tag = "3")]
        StartAction(super::StartExecute),
        /// / Informs the worker that it has been disconnected from the pool.
        /// / The worker may discard any outstanding work that is being executed.
        #[prost(message, tag = "4")]
        Disconnect(()),
        /// / Instructs the worker to kill a specific running operation.
        #[prost(message, tag = "5")]
        KillOperationRequest(super::KillOperationRequest),
        /// / Instructs the worker to touch (update access time) on blobs
        /// / to prevent premature eviction.
        #[prost(message, tag = "7")]
        TouchBlobs(super::TouchBlobsRequest),
        /// / Confirms that blobs have been persisted to stable storage.
        /// / Workers should unpin matching blobs from their local CAS.
        #[prost(message, tag = "8")]
        BlobsInStableStorage(super::BlobsInStableStorage),
        /// / Requests the worker to upload specific blobs that the server
        /// / is missing from its CAS. Sent in response to BlobsAvailable.
        #[prost(message, tag = "9")]
        UploadMissingBlobs(super::UploadMissingBlobsRequest),
        /// / Pushes a batch of small CAS/AC blobs from the server's
        /// / `SmallBlobDispatcher` to the worker. The worker writes each
        /// / `SmallBlobEntry` into `mirror_blobs` keyed by
        /// / `(store_id, digest)`. The worker subsequently advertises the
        /// / current snapshot via field 16 `pinned_mirror_entries` on the
        /// / next `BlobsAvailableNotification`, which causes the server's
        /// / per-store `EphemeralServerSidePin` set to release matching
        /// / pins.
        /// /
        /// / Backward compatibility: workers built before this field
        /// / exists treat unknown variants as ignorable warnings (the
        /// / catch-all in `local_worker.rs` `Update::*` match returns
        /// / `Ok(())` rather than `?`-propagating). NO capability flag
        /// / is required.
        #[prost(message, tag = "10")]
        BatchWriteSmallBlobs(super::BatchWriteSmallBlobsRequest),
        /// / One chunk of a streaming protocol message. Today carries
        /// / `PeerHintsChunk` (task #98); future PRs add other payload
        /// / arms (`BlobsInStableStorageChunk`, `BlobsAvailableChunk`).
        #[prost(message, tag = "11")]
        ChunkedMessage(super::ChunkedMessage),
    }
}
/// / Acknowledgement of one BlobsInStableStorageChunk delivery (task #97).
/// / Sent by the worker after every chunk it processes; the scheduler uses
/// / `(broadcast_id, sequence)` to drop the matching chunk from its
/// / per-worker resend buffer. Chunks NOT acked when the connection closes
/// / are replayed on the next ConnectWorker.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BisAck {
    #[prost(uint64, tag = "1")]
    pub broadcast_id: u64,
    #[prost(uint32, tag = "2")]
    pub sequence: u32,
}
/// / Communication from the worker to the scheduler.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateForScheduler {
    #[prost(oneof = "update_for_scheduler::Update", tags = "1, 2, 3, 4, 5, 7, 8, 9")]
    pub update: ::core::option::Option<update_for_scheduler::Update>,
}
/// Nested message and enum types in `UpdateForScheduler`.
pub mod update_for_scheduler {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Update {
        /// / The initial request sent to the scheduler informing it of the
        /// / supported properties of this worker.
        #[prost(message, tag = "1")]
        ConnectWorkerRequest(super::ConnectWorkerRequest),
        /// / Message used to let the scheduler know that it is still alive as
        /// / well as check to see if the scheduler is still alive. The scheduler
        /// / may close the connection if the worker has not sent any messages
        /// / after some amount of time (configured in the scheduler's
        /// / configuration).
        #[prost(message, tag = "2")]
        KeepAliveRequest(super::KeepAliveRequest),
        /// / Informs the scheduler that the service is going offline and
        /// / should stop issuing any new actions on this worker.
        /// /
        /// / The worker may stay connected even after sending this command
        /// / and may even send an `ExecuteResult` after sending this command.
        /// / It is up to the scheduler implementation to decide how to handle
        /// / this case.
        /// /
        /// / Any job that was running on this instance likely needs to be
        /// / executed again, but up to the scheduler on how or when to handle
        /// / this case.
        #[prost(message, tag = "3")]
        GoingAwayRequest(super::GoingAwayRequest),
        /// / Informs the scheduler about the result of an execution request.
        #[prost(message, tag = "4")]
        ExecuteResult(super::ExecuteResult),
        /// / Notify that the execution has completed, but result is uploading.
        #[prost(message, tag = "5")]
        ExecuteComplete(super::ExecuteComplete),
        /// / Notifies the scheduler that new blobs are available on this worker.
        #[prost(message, tag = "7")]
        BlobsAvailable(super::BlobsAvailableNotification),
        /// / Notifies the scheduler that blobs have been evicted from this worker.
        #[prost(message, tag = "8")]
        BlobsEvicted(super::BlobsEvictedNotification),
        /// / Acknowledges one BlobsInStableStorageChunk delivery (task #97).
        #[prost(message, tag = "9")]
        BisAck(super::BisAck),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartExecute {
    /// / The action information used to execute job.
    #[prost(message, optional, tag = "1")]
    pub execute_request: ::core::option::Option<
        super::super::super::super::super::build::bazel::remote::execution::v2::ExecuteRequest,
    >,
    /// / Id of the operation.
    #[prost(string, tag = "4")]
    pub operation_id: ::prost::alloc::string::String,
    /// / The time at which the command was added to the queue to allow population
    /// / of the ActionResult.
    #[prost(message, optional, tag = "3")]
    pub queued_timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// / The post-computed platform properties that the scheduler has reserved for
    /// / the action.
    #[prost(message, optional, tag = "5")]
    pub platform: ::core::option::Option<
        super::super::super::super::super::build::bazel::remote::execution::v2::Platform,
    >,
    /// / The ID of the worker that is executing the action.
    #[prost(string, tag = "6")]
    pub worker_id: ::prost::alloc::string::String,
    /// / Tag 8 reserved (was `peer_hints`; replaced by streaming
    /// / `ChunkedMessage::PeerHintsChunk` in #98 — peer hints chunking).
    /// / Pre-resolved input directory tree from the scheduler.
    /// / The scheduler already resolves the tree for locality scoring; including
    /// / it here lets the worker skip its own GetTree RPC. Parallel arrays:
    /// / resolved_directory_digests\[i\] is the digest of resolved_directories\[i\].
    /// / Empty when the scheduler failed to resolve the tree or it exceeded the
    /// / size threshold (worker falls back to its normal GetTree RPC).
    #[prost(message, repeated, tag = "9")]
    pub resolved_directories: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Directory,
    >,
    #[prost(message, repeated, tag = "10")]
    pub resolved_directory_digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    /// / Server-computed list of input blob digests the worker is believed to
    /// / be missing, based on the locality map snapshot at dispatch time.
    /// / When present, the worker can skip its own has_with_results check for
    /// / these digests and immediately begin fetching, saving 5-50ms of
    /// / existence-check round-trip.
    #[prost(message, repeated, tag = "11")]
    pub missing_digests: ::prost::alloc::vec::Vec<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
}
/// / This is a special message used to save actions into the CAS that can be used
/// / by programs like bb_browswer to inspect the history of a build.
/// / Note: Ensure this is always compatible with:
/// / <https://github.com/buildbarn/bb-remote-execution/blob/e95e066eb624dc9099682394ec18c12e218e8fc4/pkg/proto/cas/cas.proto#L23>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HistoricalExecuteResponse {
    #[prost(message, optional, tag = "1")]
    pub action_digest: ::core::option::Option<
        super::super::super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    #[prost(message, optional, tag = "3")]
    pub execute_response: ::core::option::Option<
        super::super::super::super::super::build::bazel::remote::execution::v2::ExecuteResponse,
    >,
}
/// Generated client implementations.
pub mod worker_api_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// / This API describes how schedulers communicate with Worker nodes.
    /// /
    /// / When a worker node comes online it must be pre-configured with the
    /// / endpoint of the scheduler it will register with. Once the worker
    /// / connects to the scheduler it must send a `ConnectWorkerRequest`
    /// / command to the scheduler. The scheduler will then use this information
    /// / to determine which jobs the worker can process.
    #[derive(Debug, Clone)]
    pub struct WorkerApiClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> WorkerApiClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> WorkerApiClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            WorkerApiClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// / Registers this worker and informs the scheduler what properties
        /// / this worker supports. The response must be listened on the client
        /// / side for updates from the server.  This is performed as a single
        /// / bi-directional call to ensure that the worker is always talking to the
        /// / same scheduler instance even if there's a load balancer in front.
        /// / The first message on the UpdateForScheduler stream will be a
        /// / ConnectWorkerRequest which will notify the scheduler of the available
        /// / properties and the first response will be a ConnectionResult to tell
        /// / the worker what worker ID to place in action results.
        pub async fn connect_worker(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::UpdateForScheduler,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::UpdateForWorker>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/com.github.trace_machina.nativelink.remote_execution.WorkerApi/ConnectWorker",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "com.github.trace_machina.nativelink.remote_execution.WorkerApi",
                        "ConnectWorker",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod worker_api_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with WorkerApiServer.
    #[async_trait]
    pub trait WorkerApi: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the ConnectWorker method.
        type ConnectWorkerStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::UpdateForWorker, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// / Registers this worker and informs the scheduler what properties
        /// / this worker supports. The response must be listened on the client
        /// / side for updates from the server.  This is performed as a single
        /// / bi-directional call to ensure that the worker is always talking to the
        /// / same scheduler instance even if there's a load balancer in front.
        /// / The first message on the UpdateForScheduler stream will be a
        /// / ConnectWorkerRequest which will notify the scheduler of the available
        /// / properties and the first response will be a ConnectionResult to tell
        /// / the worker what worker ID to place in action results.
        async fn connect_worker(
            &self,
            request: tonic::Request<tonic::Streaming<super::UpdateForScheduler>>,
        ) -> std::result::Result<
            tonic::Response<Self::ConnectWorkerStream>,
            tonic::Status,
        >;
    }
    /// / This API describes how schedulers communicate with Worker nodes.
    /// /
    /// / When a worker node comes online it must be pre-configured with the
    /// / endpoint of the scheduler it will register with. Once the worker
    /// / connects to the scheduler it must send a `ConnectWorkerRequest`
    /// / command to the scheduler. The scheduler will then use this information
    /// / to determine which jobs the worker can process.
    #[derive(Debug)]
    pub struct WorkerApiServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> WorkerApiServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for WorkerApiServer<T>
    where
        T: WorkerApi,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/com.github.trace_machina.nativelink.remote_execution.WorkerApi/ConnectWorker" => {
                    #[allow(non_camel_case_types)]
                    struct ConnectWorkerSvc<T: WorkerApi>(pub Arc<T>);
                    impl<
                        T: WorkerApi,
                    > tonic::server::StreamingService<super::UpdateForScheduler>
                    for ConnectWorkerSvc<T> {
                        type Response = super::UpdateForWorker;
                        type ResponseStream = T::ConnectWorkerStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::UpdateForScheduler>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WorkerApi>::connect_worker(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ConnectWorkerSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for WorkerApiServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "com.github.trace_machina.nativelink.remote_execution.WorkerApi";
    impl<T> tonic::server::NamedService for WorkerApiServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
