// Copyright 2024 The NativeLink Authors. All rights reserved.
//
// Licensed under the Functional Source License, Version 1.1, Apache 2.0 Future License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    See LICENSE file for details
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `nativelink-proto` crate root.
//!
//! This is a HAND-MAINTAINED file. It wires the generated proto module tree
//! (under `genproto/`, produced by `bazel run nativelink-proto:update_protos`)
//! into the crate, and adds hand-maintained, non-generated items that prost
//! cannot emit (see `type_urls`).
//!
//! The crate-level `#![allow(...)]` lints below cover the generated code. They
//! live here (not in the generated `genproto/modules.rs`) because inner
//! attributes must precede all tokens of the crate root, and `genproto/` is
//! wiped+rewritten on every regen.

#![allow(
    unknown_lints,
    unused_qualifications,
    clippy::alloc_instead_of_core,
    clippy::default_trait_access,
    clippy::derive_partial_eq_without_eq,
    clippy::doc_lazy_continuation,
    clippy::doc_link_with_quotes,
    clippy::doc_markdown,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::missing_const_for_fn,
    clippy::similar_names,
    clippy::std_instead_of_core,
    clippy::use_self,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags
)]

// Generated proto module tree (`pub mod build { ... }`, `pub mod com { ... }`,
// etc.). Auto-generated by `gen_lib_rs_tool.py`; do NOT edit by hand — run
// `bazel run nativelink-proto:update_protos`.
include!("../genproto/modules.rs");

// Hand-maintained, non-generated items.
pub mod type_urls;
